"""case and cooler tables

Revision ID: 0e9f02dc2695
Revises: a6eb10e0a906
Create Date: 2026-09-01 01:38:45.901821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9f02dc2695'
down_revision: Union[str, Sequence[str], None] = 'a6eb10e0a906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('supported_form_factors', sa.JSON(), nullable=False),
    sa.Column('max_gpu_length_mm', sa.Integer(), nullable=True),
    sa.Column('max_cooler_height_mm', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('price_range_brl_min', sa.Integer(), nullable=True),
    sa.Column('price_range_brl_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_models_model_name'), 'case_models', ['model_name'], unique=True)
    op.create_table('cooler_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('cooler_type', sa.Enum('AIR', 'AIO_LIQUID', name='coolertype'), nullable=False),
    sa.Column('supported_sockets', sa.JSON(), nullable=False),
    sa.Column('height_mm', sa.Integer(), nullable=True),
    sa.Column('radiator_size_mm', sa.Integer(), nullable=True),
    sa.Column('tdp_rating_watts', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('price_range_brl_min', sa.Integer(), nullable=True),
    sa.Column('price_range_brl_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cooler_models_model_name'), 'cooler_models', ['model_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cooler_models_model_name'), table_name='cooler_models')
    op.drop_table('cooler_models')
    op.drop_index(op.f('ix_case_models_model_name'), table_name='case_models')
    op.drop_table('case_models')
    # ### end Alembic commands ###
