"""catalog tables

Revision ID: a6eb10e0a906
Revises: 
Create Date: 2026-08-31 16:13:17.128695

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a6eb10e0a906'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpu_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('generation', sa.String(length=50), nullable=True),
    sa.Column('socket', sa.String(length=30), nullable=False),
    sa.Column('cores', sa.Integer(), nullable=True),
    sa.Column('threads', sa.Integer(), nullable=True),
    sa.Column('base_clock_ghz', sa.Float(), nullable=True),
    sa.Column('boost_clock_ghz', sa.Float(), nullable=True),
    sa.Column('tdp_watts', sa.Integer(), nullable=True),
    sa.Column('integrated_gpu', sa.String(length=100), nullable=True),
    sa.Column('pcie_version', sa.String(length=10), nullable=True),
    sa.Column('memory_types_supported', sa.JSON(), nullable=False),
    sa.Column('max_memory_speed_mhz', sa.Integer(), nullable=True),
    sa.Column('performance_tier', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('price_range_brl_min', sa.Integer(), nullable=True),
    sa.Column('price_range_brl_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpu_models_manufacturer'), 'cpu_models', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_cpu_models_model_name'), 'cpu_models', ['model_name'], unique=True)
    op.create_index(op.f('ix_cpu_models_socket'), 'cpu_models', ['socket'], unique=False)
    op.create_table('gpu_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('architecture', sa.String(length=50), nullable=True),
    sa.Column('vram_gb', sa.Integer(), nullable=True),
    sa.Column('memory_type', sa.String(length=20), nullable=True),
    sa.Column('tdp_watts', sa.Integer(), nullable=True),
    sa.Column('recommended_psu_watts', sa.Integer(), nullable=True),
    sa.Column('pcie_version', sa.String(length=10), nullable=True),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('performance_tier', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('price_range_brl_min', sa.Integer(), nullable=True),
    sa.Column('price_range_brl_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpu_models_manufacturer'), 'gpu_models', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_gpu_models_model_name'), 'gpu_models', ['model_name'], unique=True)
    op.create_table('motherboard_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('socket', sa.String(length=30), nullable=False),
    sa.Column('chipset', sa.String(length=30), nullable=False),
    sa.Column('form_factor', sa.Enum('ATX', 'MICRO_ATX', 'MINI_ITX', 'E_ATX', name='formfactor'), nullable=True),
    sa.Column('memory_type', sa.Enum('DDR3', 'DDR4', 'DDR5', name='memorytype'), nullable=False),
    sa.Column('memory_slots', sa.Integer(), nullable=True),
    sa.Column('max_memory_gb', sa.Integer(), nullable=True),
    sa.Column('max_memory_speed_mhz', sa.Integer(), nullable=True),
    sa.Column('pcie_slots', sa.JSON(), nullable=False),
    sa.Column('m2_slots', sa.Integer(), nullable=True),
    sa.Column('supports_cpu_generations', sa.JSON(), nullable=False),
    sa.Column('bios_notes', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('price_range_brl_min', sa.Integer(), nullable=True),
    sa.Column('price_range_brl_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motherboard_models_chipset'), 'motherboard_models', ['chipset'], unique=False)
    op.create_index(op.f('ix_motherboard_models_manufacturer'), 'motherboard_models', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_motherboard_models_model_name'), 'motherboard_models', ['model_name'], unique=True)
    op.create_index(op.f('ix_motherboard_models_socket'), 'motherboard_models', ['socket'], unique=False)
    op.create_table('psu_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('wattage', sa.Integer(), nullable=False),
    sa.Column('efficiency_rating', sa.String(length=30), nullable=True),
    sa.Column('modular', sa.Enum('NONE', 'SEMI', 'FULL', name='psumodular'), nullable=True),
    sa.Column('form_factor', sa.Enum('ATX', 'MICRO_ATX', 'MINI_ITX', 'E_ATX', name='formfactor'), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('price_range_brl_min', sa.Integer(), nullable=True),
    sa.Column('price_range_brl_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psu_models_model_name'), 'psu_models', ['model_name'], unique=True)
    op.create_index(op.f('ix_psu_models_wattage'), 'psu_models', ['wattage'], unique=False)
    op.create_table('ram_kit_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('memory_type', sa.Enum('DDR3', 'DDR4', 'DDR5', name='memorytype'), nullable=False),
    sa.Column('speed_mhz', sa.Integer(), nullable=False),
    sa.Column('capacity_gb_per_module', sa.Integer(), nullable=False),
    sa.Column('modules_in_kit', sa.Integer(), nullable=False),
    sa.Column('cas_latency', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('price_range_brl_min', sa.Integer(), nullable=True),
    sa.Column('price_range_brl_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ram_kit_models_memory_type'), 'ram_kit_models', ['memory_type'], unique=False)
    op.create_index(op.f('ix_ram_kit_models_model_name'), 'ram_kit_models', ['model_name'], unique=True)
    op.create_table('storage_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('storage_type', sa.Enum('HDD', 'SATA_SSD', 'NVME_SSD', name='storagetype'), nullable=False),
    sa.Column('interface', sa.String(length=50), nullable=True),
    sa.Column('form_factor', sa.String(length=30), nullable=True),
    sa.Column('capacity_gb', sa.Integer(), nullable=True),
    sa.Column('read_speed_mbps', sa.Integer(), nullable=True),
    sa.Column('write_speed_mbps', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('price_range_brl_min', sa.Integer(), nullable=True),
    sa.Column('price_range_brl_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_models_model_name'), 'storage_models', ['model_name'], unique=True)
    op.create_index(op.f('ix_storage_models_storage_type'), 'storage_models', ['storage_type'], unique=False)
    op.create_table('cpu_substitutes',
    sa.Column('cpu_id', sa.Integer(), nullable=False),
    sa.Column('substitute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cpu_id'], ['cpu_models.id'], ),
    sa.ForeignKeyConstraint(['substitute_id'], ['cpu_models.id'], ),
    sa.PrimaryKeyConstraint('cpu_id', 'substitute_id')
    )
    op.create_table('gpu_substitutes',
    sa.Column('gpu_id', sa.Integer(), nullable=False),
    sa.Column('substitute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpu_models.id'], ),
    sa.ForeignKeyConstraint(['substitute_id'], ['gpu_models.id'], ),
    sa.PrimaryKeyConstraint('gpu_id', 'substitute_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gpu_substitutes')
    op.drop_table('cpu_substitutes')
    op.drop_index(op.f('ix_storage_models_storage_type'), table_name='storage_models')
    op.drop_index(op.f('ix_storage_models_model_name'), table_name='storage_models')
    op.drop_table('storage_models')
    op.drop_index(op.f('ix_ram_kit_models_model_name'), table_name='ram_kit_models')
    op.drop_index(op.f('ix_ram_kit_models_memory_type'), table_name='ram_kit_models')
    op.drop_table('ram_kit_models')
    op.drop_index(op.f('ix_psu_models_wattage'), table_name='psu_models')
    op.drop_index(op.f('ix_psu_models_model_name'), table_name='psu_models')
    op.drop_table('psu_models')
    op.drop_index(op.f('ix_motherboard_models_socket'), table_name='motherboard_models')
    op.drop_index(op.f('ix_motherboard_models_model_name'), table_name='motherboard_models')
    op.drop_index(op.f('ix_motherboard_models_manufacturer'), table_name='motherboard_models')
    op.drop_index(op.f('ix_motherboard_models_chipset'), table_name='motherboard_models')
    op.drop_table('motherboard_models')
    op.drop_index(op.f('ix_gpu_models_model_name'), table_name='gpu_models')
    op.drop_index(op.f('ix_gpu_models_manufacturer'), table_name='gpu_models')
    op.drop_table('gpu_models')
    op.drop_index(op.f('ix_cpu_models_socket'), table_name='cpu_models')
    op.drop_index(op.f('ix_cpu_models_model_name'), table_name='cpu_models')
    op.drop_index(op.f('ix_cpu_models_manufacturer'), table_name='cpu_models')
    op.drop_table('cpu_models')
    # ### end Alembic commands ###
